UPDATE VIOLATION 
SET VIOLATION_STATUS = CASE
WHEN VIOLATION_STATUS = 'VIOLATION' THEN 'OUT OF COMPLIANCE'
ELSE 'OUT OF COMPLIANCE'
END;
insert into DBMS_FACILITY 
select DISTINCT FACILITY_ID, FACILITY_NAME, FACILITY_ADDRESS, FACILITY_ZIP, OWNER_ID from INSPECTION;
insert into DBMS_OWNER 
select distinct OWNER_ID, OWNER_NAME from INSPECTION;
insert into DBMS_REGION 
select distinct  FACILITY_ZIP, FACILITY_STATE from INSPECTION;
insert into DBMS_USER 
VALUES ('52627', '777777', '90247');
insert into DBMS_USER 
VALUES ('67890', '88888', '90201');
insert into DBMS_EXPERT 
VALUES ('67890', '67890');
insert into DBMS_CUSTOMER 
VALUES ('52627', '52627');
insert into DBMS_EMPLOYEE(EMPLOYEE_ID) 
select DISTINCT EMPLOYEE_ID from INSPECTION;
insert into DBMS_VIOLATION 
select DISTINCT VIOLATION_CODE, VIOLATION_DESCRIPTION, VIOLATION_STATUS from VIOLATION;
insert into DBMS_PE
select DISTINCT PROGRAM_ELEMENT_PE,PE_DESCRIPTION FROM INSPECTION;
insert into DBMS_PROGRAM
SELECT DISTINCT RECORD_ID, PROGRAM_NAME, PROGRAM_STATUS, EMPLOYEE_ID FROM INSPECTION;
insert into DBMS_HAVE_PE
select distinct RECORD_ID, PROGRAM_ELEMENT_PE FROM INSPECTION;
insert into DBMS_INSPECTION 
select  SERIAL_NUMBER, SCORE, GRADE, ACTIVITY_DATE, SERVICE_CODE, SERVICE_DESCRIPTION, RECORD_ID, EMPLOYEE_ID from INSPECTION;
insert into DBMS_LIE_IN
select distinct RECORD_ID, FACILITY_ID FROM INSPECTION;
insert into DBMS_VIOLATE
select  DISTINCT VIOLATION_CODE, SERIAL_NUMBER from VIOLATION WHERE SERIAL_NUMBER IN (SELECT SERIAL_NUMBER FROM INSPECTION)