CREATE TABLE DBMS_FACILITY(
"FACILITY_ID" VARCHAR2(26 BYTE),
"FACILITY_NAME" VARCHAR2(128 BYTE), 
"FACILITY_ADDRESS" VARCHAR2(128 BYTE), 
"FACILITY_ZIP" VARCHAR2(26 BYTE),
"OWNER_ID" VARCHAR2(40 BYTE),
PRIMARY KEY ("FACILITY_ID")
);
CREATE TABLE DBMS_OWNER(
"OWNER_ID" VARCHAR2(40 BYTE),
"OWNER_NAME" VARCHAR2(128 BYTE),
PRIMARY KEY ("OWNER_ID")
);
CREATE TABLE DBMS_REGION(
"ZIP" VARCHAR2(26 BYTE), 
"STATE" VARCHAR2(26 BYTE), 
PRIMARY KEY ("ZIP")
);
CREATE TABLE DBMS_USER(
"EMAIL" VARCHAR2(26 BYTE),
"USER_PASSWORD" VARCHAR2(26 BYTE),
"ZIP" VARCHAR2(26 BYTE),
PRIMARY KEY ("EMAIL")
);
CREATE TABLE DBMS_EXPERT(
"EXPERT_ID" VARCHAR2(26 BYTE),
"EMAIL" VARCHAR2(26 BYTE),
PRIMARY KEY("EXPERT_ID")
);
CREATE TABLE DBMS_CUSTOMER(
"CUSTOMER_ID" VARCHAR2(26 BYTE),
"EMAIL" VARCHAR2(26 BYTE),
PRIMARY KEY("CUSTOMER_ID")
);
CREATE TABLE DBMS_EMPLOYEE(
"EMPLOYEE_ID" VARCHAR2(50 BYTE),
"EMAIL" VARCHAR2(26 BYTE),
PRIMARY KEY("EMPLOYEE_ID")
);
CREATE TABLE DBMS_VIOLATION(
"VIOLATION_CODE" VARCHAR2(26 BYTE), 
"VIOLATION_DESCRIPTION" VARCHAR2(200 BYTE), 
"VIOLATION_STATUS" VARCHAR2(40 BYTE),
PRIMARY KEY("VIOLATION_CODE")
);
CREATE TABLE DBMS_PROGRAM(
"RECORD_ID" VARCHAR2(26 BYTE),
"PROGRAM_NAME" VARCHAR2(128 BYTE), 
"PROGRAM_STATUS" VARCHAR2(26 BYTE),
"EMPLOYEE_ID" VARCHAR2(26 BYTE),
PRIMARY KEY ("RECORD_ID"),
CONSTRAINT FK_PROGRAM_EMPLOYEE_ID FOREIGN KEY("EMPLOYEE_ID") REFERENCES "DBMS_EMPLOYEE" ("EMPLOYEE_ID")
);
CREATE TABLE DBMS_LIE_IN (
"RECORD_ID" VARCHAR2(26 BYTE),
"FACILITY_ID" VARCHAR2(26 BYTE),
CONSTRAINT DBMS_LIE_INKEY PRIMARY KEY ("RECORD_ID", "FACILITY_ID"),
CONSTRAINT FK_DBMS_LIE_IN_RECORD_ID FOREIGN KEY ("RECORD_ID") REFERENCES "DBMS_PROGRAM"("RECORD_ID"),
CONSTRAINT FK_DBMS_LIE_IN_FACILITY_ID FOREIGN KEY ("FACILITY_ID") REFERENCES "DBMS_FACILITY"("FACILITY_ID")
);
CREATE TABLE DBMS_PE(
"PROGRAM_ELEMENT_PE" NUMBER(38,0),
"PE_DESCRIPTION" VARCHAR2(128 BYTE),
primary key ("PROGRAM_ELEMENT_PE")
);
CREATE TABLE DBMS_HAVE_PE(
"RECORD_ID" VARCHAR2(26 BYTE),
"PROGRAM_ELEMENT_PE" NUMBER(38,0),
CONSTRAINT DBMS_HAVE_PEKEY PRIMARY KEY ("RECORD_ID", "PROGRAM_ELEMENT_PE"),
CONSTRAINT FK_DBMS_HAVE_PE_RECORD_ID FOREIGN KEY ("RECORD_ID") REFERENCES "DBMS_PROGRAM"("RECORD_ID"),
CONSTRAINT FK_DBMS_HAVE_PE_PROGRAM_ELEMENT_PE FOREIGN KEY ("PROGRAM_ELEMENT_PE") REFERENCES "DBMS_PE"("PROGRAM_ELEMENT_PE")
);

CREATE TABLE DBMS_INSPECTION(
"SERIAL_NUMBER" VARCHAR2(26 BYTE) ,
"SCORE" NUMBER(38,0) not null, 
"GRADE" VARCHAR2(50 BYTE) not null,
"ACTIVITY_DATE" DATE, 
"SERVICE_CODE" NUMBER(38,0),
"SERVICE_DESCRIPTION" VARCHAR2(100 BYTE),
"RECORD_ID" VARCHAR2(50 BYTE),
"EMPLOYEE_ID" VARCHAR2(50 BYTE),
PRIMARY KEY ("SERIAL_NUMBER"),
CONSTRAINT FK_INSPECTION_RECORD_ID FOREIGN KEY("RECORD_ID") REFERENCES "DBMS_PROGRAM" ("RECORD_ID"),
CONSTRAINT FK_INSPECTION_EMPLOYEE_ID FOREIGN KEY("EMPLOYEE_ID") REFERENCES "DBMS_EMPLOYEE" ("EMPLOYEE_ID")
);
CREATE TABLE DBMS_VIOLATE(
"VIOLATION_CODE" VARCHAR2(26 BYTE),
"SERIAL_NUMBER" VARCHAR2(26 BYTE) ,
CONSTRAINT DBMS_VIOLATEKEY PRIMARY KEY ("VIOLATION_CODE", "SERIAL_NUMBER"),
CONSTRAINT FK_VIOLATE_VIOLATION_CODE FOREIGN KEY ("VIOLATION_CODE") REFERENCES "DBMS_VIOLATION"("VIOLATION_CODE"),
CONSTRAINT FK_VIOLATE_SERIAL_NUMBER FOREIGN KEY ("SERIAL_NUMBER") REFERENCES "DBMS_INSPECTION"("SERIAL_NUMBER")
);
ALTER TABLE DBMS_FACILITY 
 ADD CONSTRAINT FK_FACILITY_FACILITY_ZIP FOREIGN KEY ("FACILITY_ZIP") REFERENCES "DBMS_REGION"("ZIP") INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE DBMS_FACILITY
 ADD CONSTRAINT FK_FACILITY_OWNER_ID FOREIGN KEY ("OWNER_ID") REFERENCES "DBMS_OWNER" ("OWNER_ID")INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE DBMS_EXPERT
 ADD CONSTRAINT FK_EXPERT_EMAIL FOREIGN KEY ("EMAIL") REFERENCES "DBMS_USER" ("EMAIL") INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE DBMS_CUSTOMER
 ADD CONSTRAINT FK_CUSTOMER_EMAIL FOREIGN KEY ("EMAIL") REFERENCES "DBMS_USER" ("EMAIL") INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE DBMS_EMPLOYEE
 ADD CONSTRAINT FK_EMPLOYEE_EMAIL FOREIGN KEY ("EMAIL") REFERENCES "DBMS_USER" ("EMAIL") INITIALLY DEFERRED DEFERRABLE;




